baseURL = "https://jothamlim.com"
title = "JOTHAM LIM"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true
enableRobotsTXT = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "J0THAM L1M 33 CH3N'S W3BS1TE"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Tech Hobbyist, HealthyGamer Coach & B2B Marketer"

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Welcome to my corner on the internet—where I share thoughts and insights learned throughout work and life."

    # The name to display in the copyright section in the footer
    copyrightname = "Jotham Lim"

    # Show the "built on Hugo" disclaimer
    showhugo = false
  
    showcrt = true

    # Urls for social networks
    facebook = "https://www.facebook.com/JothamLEC"
    linkedin = "https://linkedin.com/in/jothamlec"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

    FeaturedImage = "/images/f_image.jpg"

[params.copyright]
    name = "Jotham Lim"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About Me"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "post"
    name = "All Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "cool_links"
    name = "Cool Links (WIP)"
    url = "/cool_links/" 
    weight = 30

[taxonomies]
category = "category"
tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
